services:
  - type: web
    name: moviesforUs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: moviesforUs-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/static/uploads
      - key: THUMBNAIL_FOLDER
        value: /opt/render/project/src/static/thumbnails
      - key: FLASK_DEBUG
        value: 0

databases:
  - name: moviesforUs-db
    plan: free
    ipAllowList: []
    maxConnections: 20
