services:
  - type: web
    name: moviesforUs
    env: python
    region: oregon
    branch: main
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python render_deploy.py
      gunicorn --worker-tmp-dir /dev/shm app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: ADMIN_USERNAME
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      # Database Configuration
      - key: AIVEN_DB_HOST
        sync: false
      - key: AIVEN_DB_PORT
        sync: false
      - key: AIVEN_DB_NAME
        sync: false
      - key: AIVEN_DB_USER
        sync: false
      - key: AIVEN_DB_PASSWORD
        sync: false
      # Upload Configuration
      - key: UPLOAD_FOLDER
        value: static/uploads
      - key: THUMBNAIL_FOLDER
        value: static/thumbnails
    disk:
      name: uploads
      mountPath: /opt/render/project/uploads
      sizeGB: 10

databases:
  - name: moviesforUs-db
    plan: free
    ipAllowList: []
    maxConnections: 20
