services:
  - type: web
    name: moviesforus
    env: python
    region: oregon
    branch: main
    buildCommand: |
      # Install system dependencies
      apt-get update
      apt-get install -y ffmpeg python3-opencv libgl1-mesa-glx
      
      # Set up Python environment
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
      
      # Create and set permissions for upload directories
      mkdir -p /opt/render/project/src/static/uploads
      mkdir -p /opt/render/project/src/static/thumbnails
      chmod -R 755 /opt/render/project/src/static
    startCommand: |
      . venv/bin/activate
      gunicorn --worker-tmp-dir /dev/shm \
               --workers 4 \
               --threads 2 \
               --timeout 120 \
               --max-requests 1000 \
               --bind 0.0.0.0:$PORT \
               app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: ADMIN_USERNAME
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      # Database Configuration
      - key: AIVEN_DB_HOST
        sync: false
      - key: AIVEN_DB_PORT
        sync: false
      - key: AIVEN_DB_NAME
        sync: false
      - key: AIVEN_DB_USER
        sync: false
      - key: AIVEN_DB_PASSWORD
        sync: false
      # Upload Configuration
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/static/uploads
      - key: THUMBNAIL_FOLDER
        value: /opt/render/project/src/static/thumbnails
      - key: MAX_CONTENT_LENGTH
        value: "500 * 1024 * 1024"  # 500 MB upload limit
    disk:
      name: movie-storage
      mountPath: /opt/render/project/src/static
      sizeGB: 10

databases:
  - name: moviesforUs-db
    plan: free
    ipAllowList: []
    maxConnections: 20
